version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake test
workflows:
  build-and-test-stable:
    jobs:
      - build:
          matrix:
            parameters:
              # https://github.com/CircleCI-Public/cimg-ruby
              # only supports the last three ruby versions
              ruby-version:
                - "ruby:2.6.10"
                - "ruby:2.7.7"
                - "jruby:9.3.9.0"
  build-and-test-latest:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version:
                - "ruby:latest"
                - "jruby:latest"
